- name: write sysctl files so quagga works correctly on hosts
  copy: src=99cumulus_defaults dest=/etc/sysctl.d/99cumulus_defaults.conf
  notify: reload sysctl files

- name: Install iproute for Quagga dependency
  apt: name=iproute update_cache=yes state=present cache_valid_time=86400

- name: download official quagga deb
  get_url: url=https://cumulusfiles.s3.amazonaws.com/roh-3.3.0-ubuntu1604.tar validate_certs=False dest=/tmp/quagga.tar force=no

- name: Untar the package
  unarchive: src=/tmp/quagga.tar dest=/tmp/ copy=no

- name: Install Quagga
  apt: deb=/tmp/ubuntu1604/quagga_0.99.23.1-1+cl3u2_xenial_amd64.deb

- name: copy Quagga daemons
  copy: src=daemons dest=/etc/quagga/
  notify: restart quagga

- name: copy Quagga conf
  template: src=Quagga.conf.j2 dest=/etc/quagga/Quagga.conf
  notify: restart quagga

- name: start quagga
  service: name=quagga state=started

- name: Force Interfaces Down
  command: ifdown {{item}}
  with_items:
    - lo
    - eth1
    - eth2

- name: Force Interfaces Up
  command: ifup {{item}}
  with_items:
    - lo
    - eth1
    - eth2
